/* WHITE WOLF V93.7 — Study + Activity Analytics Engine
 * Read-only analytical layer. Academic study metrics use state.sessions only.
 * Other activities are available separately and are never double-counted.
 */
(function(global){'use strict';
 function num(v){var n=Number(v);return Number.isFinite(n)&&n>0?n:0}
 function dateKey(v){if(!v)return '';var s=String(v);if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);var d=new Date(v);return isNaN(d.getTime())?'':d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
 function studySessions(state){return (state.sessions||[]).map(function(s){var d=dateKey(s.date||s.started_at),m=num(s.duration||s.actualMinutes);return d&&m?Object.assign({},s,{date:d,duration:m}):null}).filter(Boolean)}
 function otherActivities(state){var out=[];(state.focusSessions||[]).forEach(function(x){var d=dateKey(x.date||x.started_at),m=num(x.actualMinutes||x.duration);if(d&&m&&!(x.type==='study'&&x.academicSessionId))out.push(Object.assign({},x,{date:d,duration:m}))});(state.activities||[]).forEach(function(x){var d=dateKey(x.date||x.started_at),m=num(x.actualMinutes||x.duration);if(d&&m&&!(x.type==='study'&&x.academicSessionId))out.push(Object.assign({},x,{date:d,duration:m}))});return out}
 function dayMap(state){var out={};studySessions(state).forEach(function(s){out[s.date]=(out[s.date]||0)+s.duration});return out}
 function activityDayMap(state){var out=dayMap(state);otherActivities(state).forEach(function(a){out[a.date]=(out[a.date]||0)+a.duration});return out}
 function daysAgo(n,base){var d=new Date(base||new Date());d.setHours(12,0,0,0);d.setDate(d.getDate()-n);return dateKey(d)}
 function rangeMinutes(state,days,offset){var map=dayMap(state),total=0,active=0,base=offset||0;for(var i=base;i<base+days;i++){var m=map[daysAgo(i)]||0;total+=m;if(m>0)active++}return{minutes:total,activeDays:active,days:days}}
 function streak(state){var map=dayMap(state),n=0;for(var i=0;i<366;i++){if((map[daysAgo(i)]||0)>0)n++;else if(i>0)break}return n}
 function bestRun(state,limit){var map=dayMap(state),best=0,run=0;for(var i=(limit||365)-1;i>=0;i--){if((map[daysAgo(i)]||0)>0){run++;best=Math.max(best,run)}else run=0}return best}
 function weekComparison(state){var cur=rangeMinutes(state,7,0),prev=rangeMinutes(state,7,7);return{current:cur,previous:prev,delta:prev.minutes?Math.round((cur.minutes-prev.minutes)/prev.minutes*100):(cur.minutes?100:0)}}
 function subjectBreakdown(state){var map={};studySessions(state).forEach(function(s){if(!s.subject_id)return;var sub=(state.subjects||[]).find(function(x){return x.id===s.subject_id}),k=s.subject_id;if(!map[k])map[k]={id:k,name:sub?sub.name:'Matière inconnue',minutes:0,sessions:0};map[k].minutes+=s.duration;map[k].sessions++});return Object.keys(map).map(function(k){var x=map[k];x.avg=Math.round(x.minutes/Math.max(1,x.sessions));return x}).sort(function(a,b){return b.minutes-a.minutes})}
 function topicBreakdown(state){var map={};studySessions(state).forEach(function(s){if(!s.topic_id)return;var t=(state.topics||[]).find(function(x){return x.id===s.topic_id}),k=s.topic_id;if(!map[k])map[k]={id:k,name:t?t.title:'Chapitre inconnu',subjectId:t?t.subject_id:null,minutes:0,sessions:0};map[k].minutes+=s.duration;map[k].sessions++});return Object.keys(map).map(function(k){var x=map[k],m=global.WWMastery&&state.mastery?global.WWMastery.evidence(state,k):null;x.mastery=m?m.stage:((state.progress&&state.progress[k]||{}).level||0);x.score=global.WWMastery?global.WWMastery.score(state,k):x.mastery*25;x.avg=Math.round(x.minutes/Math.max(1,x.sessions));return x}).sort(function(a,b){return a.score-b.score||b.minutes-a.minutes})}
 function masteryDistribution(state){var d=[0,0,0,0,0];(state.topics||[]).forEach(function(t){var l=global.WWMastery&&state.mastery?global.WWMastery.ensure(state,t.id).stage:((state.progress&&state.progress[t.id]||{}).level||0);l=Math.max(0,Math.min(4,Number(l)||0));d[l]++});return d}
 function errorStats(state){var e=state.errors||[],byStatus={to_review:0,in_progress:0,mastered:0};e.forEach(function(x){if(byStatus[x.status]!==undefined)byStatus[x.status]++});var due=e.filter(function(x){if(!x.next_review)return true;var d=new Date(x.next_review);return isNaN(d.getTime())||d.getTime()<=Date.now()}).length;return{total:e.length,due:due,byStatus:byStatus}}
 function hardestTopics(state,limit){var topics=topicBreakdown(state),errors=state.errors||[];topics.forEach(function(t){var es=errors.filter(function(e){return e.topic_id===t.id||((state.topics||[]).find(function(x){return x.id===t.id})||{}).subject_id===e.subject_id});t.errors=es.length;t.unresolved=es.filter(function(e){return e.status!=='mastered'}).length;t.heat=Math.round(t.unresolved*12+t.errors*4+Math.max(0,50-t.score))});return topics.sort(function(a,b){return b.heat-a.heat}).slice(0,limit||5)}
 function dailySeries(state,days){var map=dayMap(state),out=[];for(var i=(days||14)-1;i>=0;i--){var k=daysAgo(i);out.push({date:k,minutes:map[k]||0})}return out}
 function activitySummary(state){var ss=studySessions(state),oa=otherActivities(state),sm=ss.reduce(function(a,x){return a+x.duration},0),om=oa.reduce(function(a,x){return a+x.duration},0);return{studyMinutes:sm,otherMinutes:om,totalMinutes:sm+om,studySessions:ss.length,otherSessions:oa.length,activeDays:Object.keys(activityDayMap(state)).length}}
 function summary(state){var ss=studySessions(state),total=ss.reduce(function(a,s){return a+s.duration},0),w=rangeMinutes(state,7,0),cmp=weekComparison(state),es=errorStats(state);return{totalMinutes:total,totalHours:Math.round(total/60*10)/10,sessions:ss.length,weekMinutes:w.minutes,weekSessions:ss.filter(function(s){return dateKey(s.date)>=daysAgo(6)}).length,streak:streak(state),bestRun28:bestRun(state,28),comparison:cmp,errors:es,mastery:masteryDistribution(state),activeDays:w.activeDays,activities:activitySummary(state)}}
 global.WWAnalytics={version:'93.7',sessions:studySessions,dayMap:dayMap,activityDayMap:activityDayMap,otherActivities:otherActivities,rangeMinutes:rangeMinutes,streak:streak,bestRun:bestRun,weekComparison:weekComparison,subjectBreakdown:subjectBreakdown,topicBreakdown:topicBreakdown,masteryDistribution:masteryDistribution,errorStats:errorStats,hardestTopics:hardestTopics,dailySeries:dailySeries,activitySummary:activitySummary,summary:summary};
})(window);
